### ISSUE TITLE
Problem with display

### ISSUE THREAD

**Issue by bennyvasquez** [AlmaLinux/almalinux.org#167]
For some reason, the website doesn't seem to be using the CSS, even though (at a glance) it seems to be included. Opening this issue to keep track of this, in case it becomes a longer-term problem. The repo builds and displays correctly when I do so locally.

<img width="1139" alt="2023-04-14_14-44-35" src="https://user-images.githubusercontent.com/13630986/231966582-d86c6797-7a8b-4808-a98f-ae68aae9b04a.png">

<img width="1315" alt="2023-04-14_14-50-44" src="https://user-images.githubusercontent.com/13630986/231966591-22969c1d-39ac-4598-97a4-e0430a37f190.png">

The code of the homepage, from inspect is in this file: 
[almahomecode.txt](https://github.com/AlmaLinux/almalinux.org/files/11229902/almahomecode.txt)

**Comment by jonathanspw** [comment]
Was caused by the CSS minifier setting on CF.  Disabled it and now the issue is resolved.

**Comment by codyro** [comment]
@jonathanspw / @bennyvasquez  For what it's worth I think this may be because we're minifying this in Hugo as well so something happened with Cloudflare minimizing it in addition to Hugo.

https://github.com/AlmaLinux/almalinux.org/blob/8658bdefc68d0933280ccd4ffc97f2dee0de3f02/layouts/partials/common/head.html#L60
